pipeline:  
  build:
    image: ubuntu:latest
    commands:
      - uname -a
      - apt-get update
      - apt-get install google-chrome google-chrome-stable fluxbox firefox 
      - "export DISPLAY=:99.0"
      - "sh -e /etc/init.d/xvfb start"
      - sleep 3
      - fluxbox >/dev/null 2>&1 &
