pipeline:  
  build:
    image: alpine:latest
    commands:
      - apk --no-cache add nodejs chromium firefox-esr xvfb dbus eudev ttf-freefont fluxbox
      - apk add --update --no-cache bash chromium-doc ca-certificates hicolor-icon-theme libexif-dev pango v4l-utils-libs strace wget xdg-utils
      - npm install --production
      - npm install testcafe -g
      - npm cache clean
      - rm -rf /tmp/*
      - chmod +x ./testcafe-docker.sh
      - adduser -D user
      - ls
      - ./testcafe-docker.sh
