pipeline:  
  build:
    image: ubuntu:latest
    commands:
      - uname -a
      - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      - echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list
      - apt-get update
      - apt-get install google-chrome-stable fluxbox firefox 
      - "export DISPLAY=:99.0"
      - "sh -e /etc/init.d/xvfb start"
      - sleep 3
      - fluxbox >/dev/null 2>&1 &
