pipeline:  
  build:
    image: ubuntu:latest
    commands:
      - apt-get update
      - apt-get install -y npm nodejs nodejs-legacy chromium-browser firefox xvfb dbus ttf-freefont fluxbox wget
      - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - 
      - echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list
      - apt-get update 
      - apt-get install -y google-chrome-stable
      - wget https://ftp.mozilla.org/pub/firefox/releases/52.0/linux-x86_64/en-US/firefox-52.0.tar.bz2
      - tar -xjf firefox-52.0.tar.bz2
      - rm -rf /opt/firefox51
      - mv firefox /opt/firefox51
      - mv /usr/bin/firefox /usr/bin/firefoxold
      - ln -s /opt/firefox52/firefox /usr/bin/firefox
      - rm -rf /var/lib/apt/lists/*
      - npm install --production
      - npm install testcafe -g
      - npm cache clean
      - rm -rf /tmp/*
      - chmod +x ./testcafe-docker.sh
      - ls
      - ./testcafe-docker.sh
