pipeline:  
  chrome:
    image: ubuntu:latest
    commands:
      - apt-get update
      - apt-get install -y wget nodejs nodejs-legacy npm
      - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      - echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list
      - apt-get update
      - apt-get install -y google-chrome-stable
      - rm -rf /var/lib/apt/lists/*
      - npm install --production
      - npm install testcafe -g
      - chmod +x ./testcafe-docker.sh
      - ./testcafe-docker.sh
