pipeline:  
  build:
    image: node:latest
    commands:
      - apt install google-chrome google-chrome-stable fluxbox firefox 
      - "export DISPLAY=:99.0"
      - "sh -e /etc/init.d/xvfb start"
      - sleep 3
      - fluxbox >/dev/null 2>&1 &
