pipeline:  
  build:
    image: ubuntu:latest
    commands:
      - apt-get update
      - apt-get install -y npm nodejs chromium firefox-esr xvfb dbus ttf-freefont fluxbox
      - npm install --production
      - npm install testcafe -g
      - npm cache clean
      - rm -rf /tmp/*
      - chmod +x ./testcafe-docker.sh
      - adduser -D user
      - ls
      - ./testcafe-docker.sh
